version: "3"
    
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volunteer
      MYSQL_USER: volunteer
      MYSQL_PASSWORD: volunteer
    
  volunteer:
    depends_on:
      - db
    image: node:16
    working_dir: /home/node/app
    command: npx next dev 
    volumes:
        - ./:/home/node/app
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: volunteer
