#
# This is for local debugging only. 
#

version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volunteer_prisma
      MYSQL_USER: volunteer
      MYSQL_PASSWORD: volunteer
    
  volunteer:
    depends_on:
      - db
    image: node:16
    working_dir: /home/node/app
    command: npx next dev 
    volumes:
        - ./:/home/node/app
    ports:
      - "3000:3000"
    restart: "no"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/volunteer_prisma
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: volunteer_prisma
