apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: www-cert
spec:
  secretName: volunteerme-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'www.justvolunteerme.com'
