apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: test-cert-manager-staging
  namespace: default
spec:
  secretName: staging-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'www.justvolunteerme.com'
