# 
# Values for the cert-manager chart
#

# See here: https://github.com/jetstack/cert-manager/issues/3237
# on AWS Fargate there needs to be a non-default port. 

webhook:
  securePort: 10260

installCRDs: true

# Note: Install in the default namespace beacuse fargate is a fuck.
# helm install cert-manager jetstack/cert-manager -f values-cert-manager.yaml 
