
replicaCount: 1

image:
  repository: 957903271915.dkr.ecr.us-west-2.amazonaws.com/volunteerme
  pullPolicy: Always
  tag: "latest"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: alb
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: www.justvolunteerme.com 
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/tls-acme: "false"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  hosts:
    - name: www.justvolunteerme.com 
      awsFuckery: "true"
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: 
    - hosts:
        - www.justvolunteerme.com

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

mysql: 
  primary:
    persistence:
      enabled: 1


